version: "3.7"

services:
  php:
    image: redmine_monitor:latest
    restart: always

  nginx:
    build:
      context: ../images
      dockerfile: nginx.Dockerfile
    restart: always
    depends_on:
      - php
    ports:
      - "8001:80"
